apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-converter-deployment
  namespace: video-to-audio-converter
  labels:
    app: authconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authconverter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: authconverter
    spec:
      containers:
        - name: auth-converter
          image: gabzsz/auth_converter:cb359a1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: auth-converter-configmap
            - secretRef:
                name: auth-converter-secret